// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpjbgvmwgammfbbgzdwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwamJndm13Z2FtbWZiYmd6ZHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTczMTMsImV4cCI6MjA2NDI5MzMxM30.vVXo4LTx8-NbAP8EB4pfIL3JY3wv20zD0XIv-yyqhwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);